### PR TITLE
Implement #2 : Add repositories and install multiple php versions

### PR DESCRIPTION
**Pull request by MartinLesser**

### CODE REVIEW

**Comment by MichaelKunze** [comment]
Looks good to me

**Comment by MichaelKunze** [comment]
Could you please check it?

**Comment by MichaelKunze** [comment]
@MartinLesser Maybe mention this in the readme?

**Comment by mminks** [comment]
Ok for me now, too.

**Comment by MartinLesser** [comment]
> @MartinLesser Maybe mention this in the readme?

Done. Ready to be merged.

**Pull request merged**
